make:

assembler:
	mkdir -p ./obj/
	gcc -Wall -Wextra ./src/assembler.c ./inc/assembler.h -o ./obj/assembler

debug:
	mkdir -p ./obj/
	gcc -g -O0 -Wall -Wextra ./src/assembler.c ./inc/assembler.h -o ./obj/assembler
